Use Ubuntu for s390x
* build-files/build-image.sh
  - Common build script

* build-files/build-image.sh-ppc64le
  build-files/build-image.sh-s390x
  - Delete and use single build script

* distro/almalinux.yaml.tmpl
  - No need to create LXD base container for almalinux

* setup-build-env.sh
  - Use same build script and LXD container

Make build work as non-root

* build-files/build-image.sh
  - When building as a github action the build runs under a non-root
    user so the use of sudo is required.
  - Change creating /etc/rc.local directly to having it copied in
    by setup (otherwise EPERM)

* build-files/rc.local
  - When building under podman a `setcap` of the ping command is
    required

* setup-build-env.sh
  - Copy build-files/rc.local to the container's /etc/rc.local
  - Invoke the build script under a non-root user

diff --git a/build-files/runner-s390x.patch b/build-files/runner-s390x.patch
--- a/build-files/runner-s390x.patch
+++ b/build-files/runner-s390x.patch
@@ -1,5 +1,5 @@
 diff --git a/src/Directory.Build.props b/src/Directory.Build.props
-index 9db5faca..f02e2357 100644
+index 9db5fac..f02e235 100644
 --- a/src/Directory.Build.props
 +++ b/src/Directory.Build.props
 @@ -44,6 +44,9 @@
@@ -13,10 +13,10 @@ index 9db5faca..f02e2357 100644
    <!-- Set TRACE/DEBUG vars -->
    <PropertyGroup>
 diff --git a/src/Misc/externals.sh b/src/Misc/externals.sh
-index 997d132b..3d420a9d 100755
+index 383221e..1555f67 100755
 --- a/src/Misc/externals.sh
 +++ b/src/Misc/externals.sh
-@@ -190,3 +190,8 @@ if [[ "$PACKAGERUNTIME" == "linux-arm" ]]; then
+@@ -189,3 +189,8 @@ if [[ "$PACKAGERUNTIME" == "linux-arm" ]]; then
      acquireExternalTool "$NODE_URL/v${NODE16_VERSION}/node-v${NODE16_VERSION}-linux-armv7l.tar.gz" node16 fix_nested_dir
      acquireExternalTool "$NODE_URL/v${NODE20_VERSION}/node-v${NODE20_VERSION}-linux-armv7l.tar.gz" node20 fix_nested_dir
  fi
@@ -25,202 +25,6 @@ index 997d132b..3d420a9d 100755
 +    acquireExternalTool "$NODE_URL/v${NODE16_VERSION}/node-v${NODE16_VERSION}-linux-s390x.tar.gz" node16 fix_nested_dir
 +    acquireExternalTool "$NODE_URL/v${NODE20_VERSION}/node-v${NODE20_VERSION}-linux-s390x.tar.gz" node20 fix_nested_dir
 +fi
-diff --git a/src/Runner.Common/Constants.cs b/src/Runner.Common/Constants.cs
-index 177e3c98..6d03b799 100644
---- a/src/Runner.Common/Constants.cs
-+++ b/src/Runner.Common/Constants.cs
-@@ -58,7 +58,8 @@ namespace GitHub.Runner.Common
-             X86,
-             X64,
-             Arm,
--            Arm64
-+            Arm64,
-+            S390x
-         }
- 
-         public static class Runner
-@@ -81,6 +82,8 @@ namespace GitHub.Runner.Common
-             public static readonly Architecture PlatformArchitecture = Architecture.Arm;
- #elif ARM64
-             public static readonly Architecture PlatformArchitecture = Architecture.Arm64;
-+#elif S390X
-+            public static readonly Architecture PlatformArchitecture = Architecture.S390x;
- #else
-             public static readonly Architecture PlatformArchitecture = Architecture.X64;
- #endif
-diff --git a/src/Runner.Common/Util/VarUtil.cs b/src/Runner.Common/Util/VarUtil.cs
-index 97273a1a..2a344300 100644
---- a/src/Runner.Common/Util/VarUtil.cs
-+++ b/src/Runner.Common/Util/VarUtil.cs
-@@ -53,6 +53,8 @@ namespace GitHub.Runner.Common.Util
-                         return "ARM";
-                     case Constants.Architecture.Arm64:
-                         return "ARM64";
-+                    case Constants.Architecture.S390x:
-+                        return "S390X";
-                     default:
-                         throw new NotSupportedException(); // Should never reach here.
-                 }
-diff --git a/src/Test/L0/ConstantGenerationL0.cs b/src/Test/L0/ConstantGenerationL0.cs
-index 20424851..a9d8b465 100644
---- a/src/Test/L0/ConstantGenerationL0.cs
-+++ b/src/Test/L0/ConstantGenerationL0.cs
-@@ -20,6 +20,7 @@ namespace GitHub.Runner.Common.Tests
-                 "linux-x64",
-                 "linux-arm",
-                 "linux-arm64",
-+                "linux-s390x",
-                 "osx-x64",
-                 "osx-arm64"
-             };
-diff --git a/src/Test/L0/Listener/SelfUpdaterL0.cs b/src/Test/L0/Listener/SelfUpdaterL0.cs
-index c8383f5f..001fa838 100644
---- a/src/Test/L0/Listener/SelfUpdaterL0.cs
-+++ b/src/Test/L0/Listener/SelfUpdaterL0.cs
-@@ -16,6 +16,7 @@ using Xunit;
- 
- namespace GitHub.Runner.Common.Tests.Listener
- {
-+#if !S390X  // Self-update is not currently supported on s390x
-     public sealed class SelfUpdaterL0
-     {
-         private Mock<IRunnerServer> _runnerServer;
-@@ -795,5 +796,6 @@ namespace GitHub.Runner.Common.Tests.Listener
-             }
-         }
-     }
-+#endif
- }
- #endif
-diff --git a/src/Test/L0/PackagesTrimL0.cs b/src/Test/L0/PackagesTrimL0.cs
-index e71afd27..9fd28ec5 100644
---- a/src/Test/L0/PackagesTrimL0.cs
-+++ b/src/Test/L0/PackagesTrimL0.cs
-@@ -151,6 +151,7 @@ namespace GitHub.Runner.Common.Tests
-             }
-         }
- 
-+#if !S390X   // Self-contained publish not supported on s390x, so there is no runtime
-         [Fact]
-         [Trait("Level", "L0")]
-         [Trait("Category", "Common")]
-@@ -211,7 +212,9 @@ namespace GitHub.Runner.Common.Tests
-                 Assert.True(string.Equals(hashResult, File.ReadAllText(dotnetRuntimeHashFile).Trim()), $"Hash mismatch for dotnet runtime. You might need to update `Misc/contentHash/dotnetRuntime/{BuildConstants.RunnerPackage.PackageName}` or check if `hashFiles.ts` ever changed recently.");
-             }
-         }
-+#endif
- 
-+#if !S390X  // Self-update is not supported on s390x, so there is no need to compare hashes
-         [Fact]
-         [Trait("Level", "L0")]
-         [Trait("Category", "Common")]
-@@ -297,5 +300,6 @@ namespace GitHub.Runner.Common.Tests
-                 return Task.CompletedTask;
-             }
-         }
-+#endif
-     }
- }
-diff --git a/src/Test/L0/Worker/StepHostL0.cs b/src/Test/L0/Worker/StepHostL0.cs
-index f6b58890..421a80a0 100644
---- a/src/Test/L0/Worker/StepHostL0.cs
-+++ b/src/Test/L0/Worker/StepHostL0.cs
-@@ -55,6 +55,7 @@ namespace GitHub.Runner.Common.Tests.Worker
-             }
-         }
- 
-+#if !S390X  // Alpine not supported on s390x
-         [Fact]
-         [Trait("Level", "L0")]
-         [Trait("Category", "Worker")]
-@@ -108,6 +109,7 @@ namespace GitHub.Runner.Common.Tests.Worker
-                 Assert.Equal("node20_alpine", nodeVersion);
-             }
-         }
-+#endif
- 
-         [Fact]
-         [Trait("Level", "L0")]
-diff --git a/src/dev.sh b/src/dev.sh
-index 6a339753..f17da8b5 100755
---- a/src/dev.sh
-+++ b/src/dev.sh
-@@ -59,6 +59,7 @@ elif [[ "$CURRENT_PLATFORM" == 'linux' ]]; then
-         case $CPU_NAME in
-             armv7l) RUNTIME_ID="linux-arm";;
-             aarch64) RUNTIME_ID="linux-arm64";;
-+            s390x) RUNTIME_ID="linux-s390x";;
-         esac
-     fi
- elif [[ "$CURRENT_PLATFORM" == 'darwin' ]]; then
-@@ -85,7 +86,7 @@ if [[ "$CURRENT_PLATFORM" == 'windows' ]]; then
-         exit 1
-     fi
- elif [[ "$CURRENT_PLATFORM" == 'linux' ]]; then
--    if [[ ("$RUNTIME_ID" != 'linux-x64') && ("$RUNTIME_ID" != 'linux-x86') && ("$RUNTIME_ID" != 'linux-arm64') && ("$RUNTIME_ID" != 'linux-arm') ]]; then
-+    if [[ ("$RUNTIME_ID" != 'linux-x64') && ("$RUNTIME_ID" != 'linux-x86') && ("$RUNTIME_ID" != 'linux-arm64') && ("$RUNTIME_ID" != 'linux-arm') && ("$RUNTIME_ID" != 'linux-s390x') ]]; then
-        echo "Failed: Can't build $RUNTIME_ID package $CURRENT_PLATFORM" >&2
-        exit 1
-     fi
-@@ -308,7 +309,8 @@ function package ()
-     popd > /dev/null
- }
- 
--if [[ (! -d "${DOTNETSDK_INSTALLDIR}") || (! -e "${DOTNETSDK_INSTALLDIR}/.${DOTNETSDK_VERSION}") || (! -e "${DOTNETSDK_INSTALLDIR}/dotnet") ]]; then
-+# On linux-s390x, there is no support for dotnet-install.sh, so we must rely on a pre-installed dotnet being present
-+if [[ "${RUNTIME_ID}" != "linux-s390x" && ((! -d "${DOTNETSDK_INSTALLDIR}") || (! -e "${DOTNETSDK_INSTALLDIR}/.${DOTNETSDK_VERSION}") || (! -e "${DOTNETSDK_INSTALLDIR}/dotnet")) ]]; then
- 
-     # Download dotnet SDK to ../_dotnetsdk directory
-     heading "Ensure Dotnet SDK"
-@@ -333,8 +335,10 @@ if [[ (! -d "${DOTNETSDK_INSTALLDIR}") || (! -e "${DOTNETSDK_INSTALLDIR}/.${DOTN
-     echo "${DOTNETSDK_VERSION}" > "${DOTNETSDK_INSTALLDIR}/.${DOTNETSDK_VERSION}"
- fi
- 
--echo "Prepend ${DOTNETSDK_INSTALLDIR} to %PATH%"
--export PATH=${DOTNETSDK_INSTALLDIR}:$PATH
-+if [[ -d "${DOTNETSDK_INSTALLDIR}" ]]; then
-+    echo "Prepend ${DOTNETSDK_INSTALLDIR} to %PATH%"
-+    export PATH=${DOTNETSDK_INSTALLDIR}:$PATH
-+fi
- 
- heading "Dotnet SDK Version"
- dotnet --version
-diff --git a/src/dir.proj b/src/dir.proj
-index 056a312e..8370922e 100644
---- a/src/dir.proj
-+++ b/src/dir.proj
-@@ -41,8 +41,18 @@
-     </ItemGroup>
- 
-     <Target Name="Build" DependsOnTargets="GenerateConstant">
--        <MSBuild Targets="Restore" Projects="@(ProjectFiles)" StopOnFirstFailure="true" />
--        <MSBuild Targets="Publish" Projects="@(ProjectFiles)" BuildInParallel="false" StopOnFirstFailure="true" Properties="Configuration=$(BUILDCONFIG);PackageRuntime=$(PackageRuntime);Version=$(RunnerVersion);RuntimeIdentifier=$(PackageRuntime);PublishDir=$(MSBuildProjectDirectory)/../_layout/bin" />
-+        <PropertyGroup>
-+            <!-- Normally we want to publish a self-contained app for $(PackageRuntime) -->
-+            <PublishRuntimeIdentifier>RuntimeIdentifier=$(PackageRuntime)</PublishRuntimeIdentifier>
-+            <!-- However, on s390x there are no apphost or runtime packages on nuget.org, so self-contained publishing is not supported.
-+                 Perform a non-self-contained publish using the current runtime identifier (normally something like rhel.8-s390x) instead.
-+                 In addition, when not using an explicit runtime identifier, the SDK will copy runtime assets from dependent packages;
-+                 as this would confuse the expected layout, disable that behavior as well.  -->
-+            <PublishRuntimeIdentifier Condition="'$(PackageRuntime)' == 'linux-s390x'">SelfContained=false;CopyLocalRuntimeTargetAssets=false</PublishRuntimeIdentifier>
-+        </PropertyGroup>
-+
-+        <MSBuild Targets="Restore" Projects="@(ProjectFiles)" StopOnFirstFailure="true" Properties="$(PublishRuntimeIdentifier)" />
-+        <MSBuild Targets="Publish" Projects="@(ProjectFiles)" BuildInParallel="false" StopOnFirstFailure="true" Properties="Configuration=$(BUILDCONFIG);PackageRuntime=$(PackageRuntime);Version=$(RunnerVersion);$(PublishRuntimeIdentifier);PublishDir=$(MSBuildProjectDirectory)/../_layout/bin" />
-         <Exec Command="%22$(DesktopMSBuild)%22 Runner.Service/Windows/RunnerService.csproj /p:Configuration=$(BUILDCONFIG) /p:PackageRuntime=$(PackageRuntime) /p:OutputPath=%22$(MSBuildProjectDirectory)/../_layout/bin%22" ConsoleToMSBuild="true" Condition="'$(PackageRuntime)' == 'win-x64' Or '$(PackageRuntime)' == 'win-x86' Or '$(PackageRuntime)' == 'win-arm64'" />
-     </Target>
- 
-diff --git a/src/global.json b/src/global.json
-index 1c3ec620..04702084 100644
---- a/src/global.json
-+++ b/src/global.json
-@@ -1,5 +1,5 @@
- {
-   "sdk": {
--    "version": "6.0.415"
-+    "version": "6.0.100"
-   }
- }
 diff --git a/src/Misc/layoutroot/config.sh b/src/Misc/layoutroot/config.sh
 index 14cc6ba..9b5b8e6 100755
 --- a/src/Misc/layoutroot/config.sh
@@ -272,3 +76,179 @@ index 14cc6ba..9b5b8e6 100755
      fi
  
      if ! [ -x "$(command -v ldconfig)" ]; then
+diff --git a/src/Runner.Common/Constants.cs b/src/Runner.Common/Constants.cs
+index 177e3c9..9545981 100644
+--- a/src/Runner.Common/Constants.cs
++++ b/src/Runner.Common/Constants.cs
+@@ -58,7 +58,8 @@ namespace GitHub.Runner.Common
+             X86,
+             X64,
+             Arm,
+-            Arm64
++            Arm64,
++	    S390x
+         }
+ 
+         public static class Runner
+@@ -81,6 +82,8 @@ namespace GitHub.Runner.Common
+             public static readonly Architecture PlatformArchitecture = Architecture.Arm;
+ #elif ARM64
+             public static readonly Architecture PlatformArchitecture = Architecture.Arm64;
++#elif S390X
++            public static readonly Architecture PlatformArchitecture = Architecture.S390x;
+ #else
+             public static readonly Architecture PlatformArchitecture = Architecture.X64;
+ #endif
+diff --git a/src/Runner.Common/Util/VarUtil.cs b/src/Runner.Common/Util/VarUtil.cs
+index 97273a1..2a34430 100644
+--- a/src/Runner.Common/Util/VarUtil.cs
++++ b/src/Runner.Common/Util/VarUtil.cs
+@@ -53,6 +53,8 @@ namespace GitHub.Runner.Common.Util
+                         return "ARM";
+                     case Constants.Architecture.Arm64:
+                         return "ARM64";
++                    case Constants.Architecture.S390x:
++                        return "S390X";
+                     default:
+                         throw new NotSupportedException(); // Should never reach here.
+                 }
+diff --git a/src/Test/L0/ConstantGenerationL0.cs b/src/Test/L0/ConstantGenerationL0.cs
+index 2042485..a9d8b46 100644
+--- a/src/Test/L0/ConstantGenerationL0.cs
++++ b/src/Test/L0/ConstantGenerationL0.cs
+@@ -20,6 +20,7 @@ namespace GitHub.Runner.Common.Tests
+                 "linux-x64",
+                 "linux-arm",
+                 "linux-arm64",
++                "linux-s390x",
+                 "osx-x64",
+                 "osx-arm64"
+             };
+diff --git a/src/Test/L0/Listener/SelfUpdaterL0.cs b/src/Test/L0/Listener/SelfUpdaterL0.cs
+index 26ba65e..6791df3 100644
+--- a/src/Test/L0/Listener/SelfUpdaterL0.cs
++++ b/src/Test/L0/Listener/SelfUpdaterL0.cs
+@@ -1,4 +1,4 @@
+-﻿#if !(OS_WINDOWS && ARM64)
++﻿#if !(OS_WINDOWS && ARM64) && !S390X
+ using System;
+ using System.Collections.Generic;
+ using System.IO;
+@@ -16,6 +16,7 @@ using Xunit;
+ 
+ namespace GitHub.Runner.Common.Tests.Listener
+ {
++#if !S390X // Self-update is not currently supported on S390X
+     public sealed class SelfUpdaterL0
+     {
+         private Mock<IRunnerServer> _runnerServer;
+@@ -291,5 +292,6 @@ namespace GitHub.Runner.Common.Tests.Listener
+             }
+         }
+     }
++#endif
+ }
+ #endif
+diff --git a/src/Test/L0/Listener/SelfUpdaterV2L0.cs b/src/Test/L0/Listener/SelfUpdaterV2L0.cs
+index 5115a6b..dd8d198 100644
+--- a/src/Test/L0/Listener/SelfUpdaterV2L0.cs
++++ b/src/Test/L0/Listener/SelfUpdaterV2L0.cs
+@@ -1,4 +1,4 @@
+-﻿#if !(OS_WINDOWS && ARM64)
++﻿#if !(OS_WINDOWS && ARM64) && !S390X
+ using System;
+ using System.Collections.Generic;
+ using System.IO;
+diff --git a/src/Test/L0/Worker/StepHostL0.cs b/src/Test/L0/Worker/StepHostL0.cs
+index f6b5889..26f8e21 100644
+--- a/src/Test/L0/Worker/StepHostL0.cs
++++ b/src/Test/L0/Worker/StepHostL0.cs
+@@ -31,7 +31,7 @@ namespace GitHub.Runner.Common.Tests.Worker
+             return hc;
+         }
+ 
+-#if OS_LINUX
++#if OS_LINUX && !S390X
+         [Fact]
+         [Trait("Level", "L0")]
+         [Trait("Category", "Worker")]
+diff --git a/src/dev.sh b/src/dev.sh
+index fa637d1..8c66f37 100755
+--- a/src/dev.sh
++++ b/src/dev.sh
+@@ -54,6 +54,7 @@ elif [[ "$CURRENT_PLATFORM" == 'linux' ]]; then
+         case $CPU_NAME in
+             armv7l) RUNTIME_ID="linux-arm";;
+             aarch64) RUNTIME_ID="linux-arm64";;
++            s390x) RUNTIME_ID="linux-s390x";;
+         esac
+     fi
+ elif [[ "$CURRENT_PLATFORM" == 'darwin' ]]; then
+@@ -80,7 +81,7 @@ if [[ "$CURRENT_PLATFORM" == 'windows' ]]; then
+         exit 1
+     fi
+ elif [[ "$CURRENT_PLATFORM" == 'linux' ]]; then
+-    if [[ ("$RUNTIME_ID" != 'linux-x64') && ("$RUNTIME_ID" != 'linux-x86') && ("$RUNTIME_ID" != 'linux-arm64') && ("$RUNTIME_ID" != 'linux-arm') ]]; then
++	if [[ ("$RUNTIME_ID" != 'linux-x64') && ("$RUNTIME_ID" != 'linux-x86') && ("$RUNTIME_ID" != 'linux-arm64') && ("$RUNTIME_ID" != 'linux-arm')  && ("$RUNTIME_ID" != 'linux-s390x') ]]; then
+        echo "Failed: Can't build $RUNTIME_ID package $CURRENT_PLATFORM" >&2
+        exit 1
+     fi
+@@ -199,7 +200,8 @@ function package ()
+     popd > /dev/null
+ }
+ 
+-if [[ (! -d "${DOTNETSDK_INSTALLDIR}") || (! -e "${DOTNETSDK_INSTALLDIR}/.${DOTNETSDK_VERSION}") || (! -e "${DOTNETSDK_INSTALLDIR}/dotnet") ]]; then
++if [[ "${RUNTIME_ID}" != "linux-s390x" && ((! -d "${DOTNETSDK_INSTALLDIR}") || (! -e "${DOTNETSDK_INSTALLDIR}/.${DOTNETSDK_VERSION}") || (! -e "${DOTNETSDK_INSTALLDIR}/dotnet")) ]]; then
++
+ 
+     # Download dotnet SDK to ../_dotnetsdk directory
+     heading "Ensure Dotnet SDK"
+@@ -224,8 +226,10 @@ if [[ (! -d "${DOTNETSDK_INSTALLDIR}") || (! -e "${DOTNETSDK_INSTALLDIR}/.${DOTN
+     echo "${DOTNETSDK_VERSION}" > "${DOTNETSDK_INSTALLDIR}/.${DOTNETSDK_VERSION}"
+ fi
+ 
+-echo "Prepend ${DOTNETSDK_INSTALLDIR} to %PATH%"
+-export PATH=${DOTNETSDK_INSTALLDIR}:$PATH
++if [[ -d "${DOTNETSDK_INSTALLDIR}" ]]; then
++    echo "Prepend ${DOTNETSDK_INSTALLDIR} to %PATH%"
++    export PATH=${DOTNETSDK_INSTALLDIR}:$PATH
++fi
+ 
+ heading "Dotnet SDK Version"
+ dotnet --version
+diff --git a/src/dir.proj b/src/dir.proj
+index 056a312..8370922 100644
+--- a/src/dir.proj
++++ b/src/dir.proj
+@@ -41,8 +41,18 @@
+     </ItemGroup>
+ 
+     <Target Name="Build" DependsOnTargets="GenerateConstant">
+-        <MSBuild Targets="Restore" Projects="@(ProjectFiles)" StopOnFirstFailure="true" />
+-        <MSBuild Targets="Publish" Projects="@(ProjectFiles)" BuildInParallel="false" StopOnFirstFailure="true" Properties="Configuration=$(BUILDCONFIG);PackageRuntime=$(PackageRuntime);Version=$(RunnerVersion);RuntimeIdentifier=$(PackageRuntime);PublishDir=$(MSBuildProjectDirectory)/../_layout/bin" />
++        <PropertyGroup>
++            <!-- Normally we want to publish a self-contained app for $(PackageRuntime) -->
++            <PublishRuntimeIdentifier>RuntimeIdentifier=$(PackageRuntime)</PublishRuntimeIdentifier>
++            <!-- However, on s390x there are no apphost or runtime packages on nuget.org, so self-contained publishing is not supported.
++                 Perform a non-self-contained publish using the current runtime identifier (normally something like rhel.8-s390x) instead.
++                 In addition, when not using an explicit runtime identifier, the SDK will copy runtime assets from dependent packages;
++                 as this would confuse the expected layout, disable that behavior as well.  -->
++            <PublishRuntimeIdentifier Condition="'$(PackageRuntime)' == 'linux-s390x'">SelfContained=false;CopyLocalRuntimeTargetAssets=false</PublishRuntimeIdentifier>
++        </PropertyGroup>
++
++        <MSBuild Targets="Restore" Projects="@(ProjectFiles)" StopOnFirstFailure="true" Properties="$(PublishRuntimeIdentifier)" />
++        <MSBuild Targets="Publish" Projects="@(ProjectFiles)" BuildInParallel="false" StopOnFirstFailure="true" Properties="Configuration=$(BUILDCONFIG);PackageRuntime=$(PackageRuntime);Version=$(RunnerVersion);$(PublishRuntimeIdentifier);PublishDir=$(MSBuildProjectDirectory)/../_layout/bin" />
+         <Exec Command="%22$(DesktopMSBuild)%22 Runner.Service/Windows/RunnerService.csproj /p:Configuration=$(BUILDCONFIG) /p:PackageRuntime=$(PackageRuntime) /p:OutputPath=%22$(MSBuildProjectDirectory)/../_layout/bin%22" ConsoleToMSBuild="true" Condition="'$(PackageRuntime)' == 'win-x64' Or '$(PackageRuntime)' == 'win-x86' Or '$(PackageRuntime)' == 'win-arm64'" />
+     </Target>
+ 
+diff --git a/src/global.json b/src/global.json
+index b014aea..0470208 100644
+--- a/src/global.json
++++ b/src/global.json
+@@ -1,5 +1,5 @@
+ {
+   "sdk": {
+-    "version": "6.0.418"
++    "version": "6.0.100"
+   }
+ }
